<?php

use Illuminate\Database\Seeder;
use App\Category;

class CategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
		$names = [
		'Actor/Director',
		'Movie',
		'Producer',
		'Writer',
		'Studio',
		'Movie Theater',
		'TV/Movie Award',
		'Fictional Character',
		'Album',
		'Song',
		'Musician/Band',
		'Musical Instrument',
		'Playlist',
		'Music Video',
		'Concert Tour',
		'Concert Venue',
		'Radio Station',
		'Record Label',
		'Music Award',
		'Music Chart',
		'Book',
		'Author',
		'Book Store',
		'Library',
		'Magazine',
		'Editor',
		'TV Show',
		'TV Network',
		'TV Channel',
		'Athlete',
		'Artist',
		'Public Figure',
		'Journalist',
		'News Personality',
		'Chef',
		'Lawyer',
		'Doctor',
		'Business Person',
		'Comedian',
		'Entertainer',
		'Monarch',
		'Teacher',
		'Dancer',
		'Politician',
		'Government Official',
		'Sports League',
		'Professional Sports Team',
		'Coach',
		'Amateur Sports Team',
		'School Sports Team',
		'Restaurant/Cafe',
		'Bar',
		'Club',
		'Company',
		'Product/Service',
		'Website',
		'Cars',
		'Bags/Luggage',
		'Camera/Photo',
		'Clothing',
		'Computers',
		'Software',
		'Office Supplies',
		'Electronics',
		'Health/Beauty',
		'Appliances',
		'Building Materials',
		'Commercial Equipment',
		'Home Decor',
		'Furniture',
		'Household Supplies',
		'Kitchen/Cooking',
		'Patio/Garden',
		'Tools/Equipment',
		'Wine/Spirits',
		'Jewelry/Watches',
		'Movies/Music',
		'Pet Supplies',
		'Outdoor Gear/Sporting Goods',
		'Baby Goods/Kids Goods',
		'Media/News/Publishing',
		'Bank/Financial Institution',
		'Non-Governmental Organization (NGO)',
		'Insurance Company',
		'Small Business',
		'Energy/Utility',
		'Retail and Consumer Merchandise',
		'Automobiles and Parts',
		'Industrials',
		'Transport/Freight',
		'Health/Medical/Pharmaceuticals',
		'Aerospace/Defense',
		'Mining/Materials',
		'Farming/Agriculture',
		'Chemicals',
		'Consulting/Business Services',
		'Legal/Law',
		'Education',
		'Engineering/Construction',
		'Food/Beverages',
		'Telecommunication',
		'Biotechnology',
		'Computers/Technology',
		'Internet/Software',
		'Travel/Leisure',
		'Community Organization',
		'Political Organization',
		'Vitamins/Supplements',
		'Drugs',
		'Church/Religious Organization',
		'Games/Toys',
		'App',
		'Local Business',
		'Hotel',
		'Landmark',
		'Transit Stop',
		'Airport',
		'Sports Venue',
		'Arts/Entertainment/Nightlife',
		'Automotive',
		'Spas/Beauty/Personal Care',
		'Event Planning/Event Services',
		'Bank/Financial Services',
		'Food/Grocery',
		'Health/Medical/Pharmacy',
		'Home Improvement',
		'Pet Services',
		'Professional Services',
		'Business Services',
		'Community/Government',
		'Real Estate',
		'Shopping/Retail',
		'Public Places',
		'Attractions/Things to Do',
		'Sports/Recreation/Activities',
		'Tours/Sightseeing',
		'Transportation',
		'Hospital/Clinic',
		'Museum/Art Gallery',
		'Organization',
		'School',
		'University',
		'Non-Profit Organization',
		'Government Organization',
		'Cause',
		'Political Party'
		];
		foreach ($names as $name) {
			(new Category(compact('name')))
				->save();
		}
    }
}
