<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/vue/0.11.10/vue.min.js"></script>
<script src="{{ asset('vendor/neon/js/gsap/main-gsap.js') }}"></script>
<script src="{{ asset('vendor/neon/js/joinable.js') }}"></script>
<script src="{{ asset('vendor/neon/js/resizeable.js') }}"></script>
<script src="{{ asset('vendor/neon/js/neon-api.js') }}"></script>
<script src="{{ asset('vendor/neon/js/neon-custom.js') }}"></script>
<script type="text/javascript">@yield('js')</script>